import os
import asyncio
from typing import List, Dict
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request
import google.oauth2.credentials
import httpx

from adapters.base_adapter import StreamingAdapter
from config import YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, YOUTUBE_REDIRECT_URI

# The scope required to read and manage the user's YouTube account and playlists
SCOPES = ["https://www.googleapis.com/auth/youtube"]

class YouTubeAdapter(StreamingAdapter):
    def __init__(self):
        self.youtube = None
        self.credentials = None

    async def authenticate(self) -> bool:
        """Handles local browser-based OAuth 2.0 authentication for Google."""
        client_config = {
            "web": {
                "client_id": YOUTUBE_CLIENT_ID,
                "client_secret": YOUTUBE_CLIENT_SECRET,
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "redirect_uris": [YOUTUBE_REDIRECT_URI]
            }
        }

        # Run a local webserver on port 8080 to receive the authentication token
        flow = InstalledAppFlow.from_client_config(client_config, scopes=SCOPES)
        
        # Run this block in a separate thread to prevent blocking the async loop
        loop = asyncio.get_running_loop()
        self.credentials = await loop.run_in_executor(
            None, 
            lambda: flow.run_local_server(port=8080, prompt="select_account")
        )
        
        if self.credentials and self.credentials.valid:
            self.youtube = build("youtube", "v3", credentials=self.credentials)
            print("🔑 YouTube successfully authenticated!")
            return True
        return False

    async def fetch_playlist(self, playlist_id: str) -> List[Dict]:
        """Pulls a YouTube playlist and normalizes the metadata payload."""
        if not self.youtube:
            raise Exception("Adapter not authenticated. Call authenticate() first.")

        normalized_tracks = []
        
        # Execute the synchronous Google SDK request inside an executor pool
        def _get_items():
            return self.youtube.playlistItems().list(
                part="snippet,contentDetails",
                playlistId=playlist_id,
                maxResults=50
            ).execute()

        loop = asyncio.get_running_loop()
        response = await loop.run_in_executor(None, _get_items)

        for item in response.get("items", []):
            snippet = item.get("snippet", {})
            video_id = snippet.get("resourceId", {}).get("videoId")
            title = snippet.get("title")
            video_owner = snippet.get("videoOwnerChannelTitle", "")
            
            # Clean up the channel name (e.g., "HarryStylesVEVO" -> "Harry Styles")
            artist = video_owner.replace("VEVO", "").replace(" - Topic", "").strip()

            # YouTube video snippets do not contain global ISRCs natively.
            # We initialize it as None. The orchestrator will match or look it up.
            normalized_tracks.append({
                "vendor_id": video_id,
                "title": title,
                "artist": artist,
                "isrc": None  
            })

        return normalized_tracks

    async def create_safe_playlist(self, safe_vendor_ids: List[str], original_name: str) -> str:
        """Creates a brand new sanitized playlist and populates it with safe video IDs."""
        if not self.youtube:
            raise Exception("Adapter not authenticated.")

        loop = asyncio.get_running_loop()

        # Step A: Create the empty playlist container
        def _create_playlist():
            return self.youtube.playlists().insert(
                part="snippet,status",
                body={
                    "snippet": {
                        "title": f"[Safe] {original_name}",
                        "description": "Sanitized child-safe playlist generated by Audio Curator."
                    },
                    "status": {
                        "privacyStatus": "private"
                    }
                }
            ).execute()

        playlist_res = await loop.run_in_executor(None, _create_playlist)
        new_playlist_id = playlist_res.get("id")

        # Step B: Inject each safe video ID into the new playlist container
        for video_id in safe_vendor_ids:
            def _add_video(v_id):
                return self.youtube.playlistItems().insert(
                    part="snippet",
                    body={
                        "snippet": {
                            "playlistId": new_playlist_id,
                            "resourceId": {
                                "kind": "youtube#video",
                                "videoId": v_id
                            }
                        }
                    }
                ).execute()
            
            await loop.run_in_executor(None, _add_video, video_id)
            await asyncio.sleep(0.2)  # Avoid hitting YouTube rate limits too fast

        return f"https://music.youtube.com/playlist?list={new_playlist_id}"